nodes:
- input.visual:
    source: "C:\\Users\\jlwq0\\Documents\\JoyLinWQ\\peekingduck_idea\\data\\trim3.mp4"
- model.efficientdet:
    detect_ids: ["car", "motorcycle", "truck", "bus"]
    score_threshold: 0.3 # default 0.3
- dabble.tracking:
    tracking_type: "iou"
- dabble.statistics:
    maximum: obj_attrs["ids"]
- dabble.bbox_to_btm_midpoint
- dabble.zone_count:
    resolution: [1280, 720]
    zones: [
        [[0, 0], [0.55, 0], [0.55, 1], [0, 1]],
        [[0.55, 0], [1, 0], [1, 1], [0.55, 1]]
    ]
- dabble.bbox_count
- draw.legend:
    show: ["zone_count"]
    # detect_ids: ["car", "motorcycle", "truck", "bus"]
    # show: ["cum_max"]
- draw.bbox:
    show_labels: True
- draw.btm_midpoint
- draw.zones
- draw.tag:
    show: ["ids"]
# - draw.legend:
    # show: ["zone_count"]
    # detect_ids: ["car", "motorcycle", "truck", "bus"]
    # show: ["cum_max"]
- output.screen
- output.media_writer

# running peekingduck command
# peekingduck run --config_path "C:\\Users\\jlwq0\\Documents\\JoyLinWQ\\peekingduck_idea\\src\\custom_nodes\\configs\\object_counting_over_time.yml"
# peekingduck run --config_path "C:\\Users\\jlwq0\\Documents\\JoyLinWQ\\peekingduck_idea\\src\\custom_nodes\\configs\\custom_config.yml"