nodes:
- input.visual:
    source: data\sample_traffic.mp4
- model.efficientdet:
    detect_ids: ["car", "motorcycle", "truck", "bus"]
    score_threshold: 0.3 # default 0.3
- dabble.tracking:
    tracking_type: "iou"
- dabble.statistics:
    maximum: obj_attrs["ids"]
- dabble.bbox_to_btm_midpoint
- dabble.zone_count:
    resolution: [1280, 720]
    zones: [
        [[0, 0], [0.55, 0], [0.55, 1], [0, 1]],
        [[0.55, 0], [1, 0], [1, 1], [0.55, 1]]
    ]
- dabble.bbox_count
- draw.bbox:
    show_labels: True
- draw.btm_midpoint
- draw.zones
- draw.tag:
    show: ["ids"]
- custom_nodes.draw.legend:
    show: ["zone_count"]
- output.screen
- output.media_writer
