nodes:
- input.visual:
    source: data/trim3.mp4
- model.efficientdet
- dabble.tracking
- dabble.statistics
- dabble.bbox_to_btm_midpoint
- dabble.zone_count
- draw.bbox
- draw.btm_midpoint
- draw.zones
- draw.tag
- custom_nodes.draw.legend:
    show: ["zone_count"]
- output.screen
- output.media_writer
