# Mandatory configs
# Receive bounding boxes and their respective labels as input. Replace with
# other data types as required. List of built-in data types for PeekingDuck can
# be found at https://peekingduck.readthedocs.io/en/stable/glossary.html.
# input: ["bboxes", "bbox_labels", "my_ids"]
# input: ["bboxes", "bbox_labels", "bbox_scores", "btm_midpoint", "my_ids"]
input: ["all"]

# Example:
# Output `obj_attrs` for visualization with `draw.tag` node and `custom_key` for
# use with other custom nodes. Replace as required.
output: ["obj_attrs", "bboxes", "bbox_labels", "bbox_scores", "zones", "zone_count", "my_ids"]
# output: ["all"]

# Optional configs depending on node
# threshold: 0.5 # example
resolution: [1280, 720] # Used only in fraction mode

zones: [
    [[0, 0], [0.55, 0], [0.55, 1], [0, 1]],
    [[0.55, 0], [1, 0], [1, 1], [0.55, 1]]
]
