# Mandatory configs
# Receive bounding boxes and their respective labels as input. Replace with
# other data types as required. List of built-in data types for PeekingDuck can
# be found at https://peekingduck.readthedocs.io/en/stable/glossary.html.
# input: ["bboxes", "bbox_labels"]
# Example:
# Output `obj_attrs` for visualization with `draw.tag` node and `custom_key` for
# use with other custom nodes. Replace as required.
# output: ["obj_attrs", "custom_key"]

# Optional configs depending on node
# threshold: 0.5 # example

input: ["all"]
output: ["img"]

position: "bottom"
show: []
# Amend this class names dictionary accordingly to your desired
# List of built-in data types for PeekingDuck can
# be found at https://peekingduck.readthedocs.io/en/stable/glossary.html.
custom_class_names: {"car": 2, "motorcycle": 3, "truck": 5, "bus": 7}
# custom_class_names: {"bird": 15, "horse": 18, "sheep": 19, "cow": 20, "elephant": 21, "bear": 22, "zebra":23, "giraffe": 24}